name: Release Asset Creation

on:
  release:
    types: [ created ]

jobs:
  create-release-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y zip

      - name: Create archive
        run: |
          zip -r main.zip ./main/*

      - name: Rename archive to .dslibrary
        run: mv main.zip main.dslibrary

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          name: release-asset
          path: main.dslibrary

      - name: Create release (optional)
        uses: actions/create-release@v1
        if: ${{ github.event.name == 'release' && github.event.release.draft == false }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}  # Customize release name if desired
          body: ${{ github.event.release.body }}  # Optional release description
          draft: false
          prerelease: false  # Set to true for prereleases

